/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

/**
 *
 * @author HP
 */
public class Add_Product extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Add_Product.class.getName());
    private java.util.Map<String, Integer> categoryMap = new java.util.HashMap<>();
    private java.util.Map<String, Integer> supplierMap = new java.util.HashMap<>();
    /**
     * Creates new form NewJDialog
     */
    public Add_Product(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadCategories();
        loadSuppliers();
    }
    
    private void loadCategories() {
        cmbCategory.removeAllItems();
        String sql = "SELECT category_id, category_name FROM product_categories";
        try (java.sql.Connection conn = CODE.DBConnection.getConnection();
             java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
             java.sql.ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                String name = rs.getString("category_name");
                int id = rs.getInt("category_id");
                categoryMap.put(name, id);
                cmbCategory.addItem(name);
            }
        } catch (java.sql.SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Failed to load categories", e);
        }
    }

    private void loadSuppliers() {
        cmbSupplier.removeAllItems();
        cmbSupplier.addItem("None");
        String sql = "SELECT supplier_id, supplier_name FROM suppliers WHERE status = 'Active'";
        try (java.sql.Connection conn = CODE.DBConnection.getConnection();
             java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
             java.sql.ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                String name = rs.getString("supplier_name");
                int id = rs.getInt("supplier_id");
                supplierMap.put(name, id);
                cmbSupplier.addItem(name);
            }
        } catch (java.sql.SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Failed to load suppliers", e);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblProduct = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblSKU = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblReorder = new javax.swing.JTextField();
        lblStock = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        cmbCategory = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("INVENTORY & PRODUCT MANAGEMENT");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Product name ");

        lblProduct.addActionListener(this::lblProductActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("SKU");

        lblSKU.addActionListener(this::lblSKUActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Price (Rs.)");

        lblPrice.addActionListener(this::lblPriceActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Initial Stock");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Reorder Level");

        lblReorder.addActionListener(this::lblReorderActionPerformed);

        lblStock.addActionListener(this::lblStockActionPerformed);

        btnSave.setBackground(new java.awt.Color(11, 107, 109));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save Product");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        cmbCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCategory.addActionListener(this::cmbCategoryActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Category");

        cmbSupplier.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Supplier ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProduct)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(lblSKU)
                                    .addComponent(lblStock, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblReorder, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(56, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSKU, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReorder, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProductActionPerformed

    private void lblSKUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblSKUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSKUActionPerformed

    private void lblPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPriceActionPerformed

    private void lblReorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblReorderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblReorderActionPerformed

    private void lblStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblStockActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
    try {
        // 1. Retrieve text inputs
        String productName = lblProduct.getText().trim();
        String sku = lblSKU.getText().trim();
        String priceText = lblPrice.getText().trim();
        String stockText = lblStock.getText().trim();
        String reorderText = lblReorder.getText().trim();

        // 2. Validate empty fields
        if (productName.isEmpty() || sku.isEmpty() || priceText.isEmpty() || stockText.isEmpty() || reorderText.isEmpty()) {
            throw new IllegalArgumentException("All fields are required. Please complete all inputs.");
        }

        // 3. Validate Product Name
        if (!productName.matches("[a-zA-Z0-9\\s.,'-]+")) {
            throw new IllegalArgumentException("Product Name contains invalid characters.");
        }

        // 4. Validate Price
        double price;
        try {
            price = Double.parseDouble(priceText);
            if (price < 0) throw new IllegalArgumentException("Price cannot be negative.");
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Price must be a valid number.");
        }

        // 5. Validate Stock
        int stock;
        try {
            stock = Integer.parseInt(stockText);
            if (stock < 0) throw new IllegalArgumentException("Initial Stock cannot be negative.");
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Initial Stock must be a whole number.");
        }

        // 6. Validate Reorder Level
        int reorderLevel;
        try {
            reorderLevel = Integer.parseInt(reorderText);
            if (reorderLevel < 0) throw new IllegalArgumentException("Reorder Level cannot be negative.");
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Reorder Level must be a whole number.");
        }

        // 6b. Validate Category (mandatory)
        String selectedCategory = (String) cmbCategory.getSelectedItem();
        if (selectedCategory == null) {
            throw new IllegalArgumentException("Please select a category.");
        }
        int categoryId = categoryMap.get(selectedCategory);

        // 6c. Resolve Supplier (optional — "None" means NULL)
        String selectedSupplier = (String) cmbSupplier.getSelectedItem();
        Integer supplierId = (selectedSupplier == null || selectedSupplier.equals("None"))
                ? null
                : supplierMap.get(selectedSupplier);

        // 7. Insert into products + inventory in a single transaction
        java.sql.Connection conn = null;
        try {
            conn = CODE.DBConnection.getConnection();
            conn.setAutoCommit(false);

            String insertProduct = "INSERT INTO products (category_id, supplier_id, product_name, sku, unit_price, unit_of_measure, status) "
                                  + "VALUES (?, ?, ?, ?, ?, 'piece', 'Active')";
            int newProductId;

            try (java.sql.PreparedStatement pstmt = conn.prepareStatement(insertProduct, java.sql.Statement.RETURN_GENERATED_KEYS)) {
                pstmt.setInt(1, categoryId);
                if (supplierId == null) {
                    pstmt.setNull(2, java.sql.Types.INTEGER);
                } else {
                    pstmt.setInt(2, supplierId);
                }
                pstmt.setString(3, productName);
                pstmt.setString(4, sku);
                pstmt.setDouble(5, price);
                pstmt.executeUpdate();

                try (java.sql.ResultSet keys = pstmt.getGeneratedKeys()) {
                    if (keys.next()) {
                        newProductId = keys.getInt(1);
                    } else {
                        throw new java.sql.SQLException("Failed to retrieve generated product ID.");
                    }
                }
            }

            String insertInventory = "INSERT INTO inventory (product_id, quantity_on_hand, reorder_level, last_restocked_at) "
                                    + "VALUES (?, ?, ?, NOW())";
            try (java.sql.PreparedStatement pstmt = conn.prepareStatement(insertInventory)) {
                pstmt.setInt(1, newProductId);
                pstmt.setInt(2, stock);
                pstmt.setInt(3, reorderLevel);
                pstmt.executeUpdate();
            }

            conn.commit();

            if (getParent() instanceof Inventory_and_product_management) {
                ((Inventory_and_product_management) getParent()).loadProducts();
            }

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Product added successfully!", "Success",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

        } catch (java.sql.SQLIntegrityConstraintViolationException dupEx) {
            if (conn != null) try { conn.rollback(); } catch (java.sql.SQLException ignored) {}
            javax.swing.JOptionPane.showMessageDialog(this,
                    "A product with this SKU already exists.", "Duplicate SKU",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (java.sql.SQLException dbEx) {
            if (conn != null) try { conn.rollback(); } catch (java.sql.SQLException ignored) {}
            logger.log(java.util.logging.Level.SEVERE, "Error saving product", dbEx);
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Database error: " + dbEx.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } finally {
            if (conn != null) {
                try { conn.setAutoCommit(true); conn.close(); } catch (java.sql.SQLException ignored) {}
            }
        }

    } catch (IllegalArgumentException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Validation Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }

          
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Add_Product dialog = new Add_Product(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lblPrice;
    private javax.swing.JTextField lblProduct;
    private javax.swing.JTextField lblReorder;
    private javax.swing.JTextField lblSKU;
    private javax.swing.JTextField lblStock;
    // End of variables declaration//GEN-END:variables
}
