/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import CODE.PasswordUtil;
import java.sql.SQLIntegrityConstraintViolationException;
import CODE.Session;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
/**
 *
 * @author tharu
 */
public class Create_user extends javax.swing.JFrame {
    
    private String selectedRole = null;
    private ManageStaff parentList = null;   // staff list to refresh after saving (null = opened from login)
    private Integer editUserId = null;       // null = create new account, a number = editing that account
    private String currentStatus = "Active";    
    /**
     * Creates new form Create_user
     */
    public Create_user() {
        this(null, null);   // opened from the login screen
    }

    // CREATE mode - "+ Create Account" on Manage Staff
    public Create_user(ManageStaff parentList) {
        this(parentList, null);
    }

    // EDIT mode - "edit" button on Manage Staff
    public Create_user(ManageStaff parentList, Integer editUserId) {
        initComponents();
        this.parentList = parentList;
        this.editUserId = editUserId;

        btnCashier.addActionListener(evt -> { selectedRole = "Cashier"; showSelectedRole(); });
        btnAdmin.addActionListener(evt -> { selectedRole = "Admin"; showSelectedRole(); });
        btnback.addActionListener(evt -> backToSignIn());

        if (parentList != null) {
            btnback.setText("<-- Back to staff list");
        }

        if (editUserId != null) {
            jLabel2.setText("Edit Staff Account");
            jLabel5.setText("New Password");
            btnCreateAcc.setText("Update Account");
            txtpassword.setToolTipText("Leave empty to keep the current password");
            txtconfirm.setToolTipText("Leave empty to keep the current password");
            loadUser(editUserId);
        }
    }

    // Fills the form with the staff member's current details (edit mode)
    private void loadUser(int userId) {
        String sql = "SELECT full_name, username, role, status FROM users WHERE user_id = ?";
        try (Connection conn = CODE.DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, userId);
            try (java.sql.ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    lblfullname.setText(rs.getString("full_name"));
                    txtusername.setText(rs.getString("username"));
                    selectedRole = rs.getString("role");
                    currentStatus = rs.getString("status");
                    showSelectedRole();
                } else {
                    JOptionPane.showMessageDialog(this, "This staff account no longer exists.",
                        "Not Found", JOptionPane.WARNING_MESSAGE);
                    btnCreateAcc.setEnabled(false);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
            btnCreateAcc.setEnabled(false);
        }
    }

    // Colours the chosen role button so you can see which role is selected
    private void showSelectedRole() {
        boolean cashier = "Cashier".equals(selectedRole);
        boolean admin = "Admin".equals(selectedRole);
        btnCashier.setBackground(cashier ? new java.awt.Color(11, 107, 109) : null);
        btnCashier.setForeground(cashier ? java.awt.Color.WHITE : java.awt.Color.BLACK);
        btnAdmin.setBackground(admin ? new java.awt.Color(11, 107, 109) : null);
        btnAdmin.setForeground(admin ? java.awt.Color.WHITE : java.awt.Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblfullname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtconfirm = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        btnCashier = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnCreateAcc = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 245, 242));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Samadhi Pooja Stores");

        btnback.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnback.setText("<-- Back to sign in?");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Create Staff Account");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Full Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("UserName");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Confirm Password");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Role");

        btnCashier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCashier.setText("Cashier");

        btnAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdmin.setText("Admin");

        btnCreateAcc.setBackground(new java.awt.Color(11, 107, 109));
        btnCreateAcc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCreateAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateAcc.setText("Create Account");
        btnCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnback))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(lblfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6)
                                    .addGap(73, 73, 73)))
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCashier, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txtpassword))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtconfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(btnAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnCreateAcc)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnback)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreateAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccActionPerformed
        String fullName = lblfullname.getText().trim();
        String username = txtusername.getText().trim();
        char[] passwordChars = txtpassword.getPassword();
        char[] confirmChars = txtconfirm.getPassword();
        String password = new String(passwordChars).trim();
        String confirm = new String(confirmChars).trim();
//error Exception

        if (fullName.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Full name cannot be empty.", "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            lblfullname.requestFocus();
            return;
        }

        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Username cannot be empty.", "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            txtusername.requestFocus();
            return;
        }

        if (username.contains(" ")) {
            JOptionPane.showMessageDialog(this,
                "Username cannot contain spaces.", "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            txtusername.requestFocus();
            return;
        }

        // Edit mode: the password is optional. Leave both boxes empty to keep the old one.
        boolean changePassword = (editUserId == null) || !password.isEmpty() || !confirm.isEmpty();

        if (changePassword) {
            if (password.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "Password cannot be empty.", "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
                txtpassword.requestFocus();
                return;
            }

            if (password.length() < 6) {
                JOptionPane.showMessageDialog(this,
                    "Password must be at least 6 characters.", "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
                txtpassword.requestFocus();
                return;
            }

            if (!password.equals(confirm)) {
                JOptionPane.showMessageDialog(this,
                    "Passwords do not match.", "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
                txtconfirm.requestFocus();
                return;
            }
        }

        if (selectedRole == null) {
            JOptionPane.showMessageDialog(this,
                "Please select a role (Cashier or Admin).", "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        String hashedPassword = changePassword ? PasswordUtil.hash(passwordChars) : null;

        // Edit mode: if the account is Inactive, ask whether to switch it back on
        String newStatus = currentStatus;
        if (editUserId != null && "Inactive".equals(currentStatus)) {
            int answer = JOptionPane.showConfirmDialog(this,
                "This account is Inactive, so this person can't sign in.\nMake it Active again?",
                "Account Status", JOptionPane.YES_NO_OPTION);
            if (answer == JOptionPane.YES_OPTION) {
                newStatus = "Active";
            }
        }

        try (Connection conn = CODE.DBConnection.getConnection()) {
            if (editUserId == null) {
                // CREATE
                String sql = "INSERT INTO users (username, password_hash, full_name, role, created_by) "
                           + "VALUES (?, ?, ?, ?, ?)";
                try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                    pstmt.setString(1, username);
                    pstmt.setString(2, hashedPassword);
                    pstmt.setString(3, fullName);
                    pstmt.setString(4, selectedRole);
                    pstmt.setInt(5, Session.getCurrentUserId());
                    pstmt.executeUpdate();
                }
            } else {
                // UPDATE (the password only changes if a new one was typed)
                String sql = changePassword
                    ? "UPDATE users SET full_name = ?, username = ?, role = ?, status = ?, password_hash = ? WHERE user_id = ?"
                    : "UPDATE users SET full_name = ?, username = ?, role = ?, status = ? WHERE user_id = ?";
                try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                    pstmt.setString(1, fullName);
                    pstmt.setString(2, username);
                    pstmt.setString(3, selectedRole);
                    pstmt.setString(4, newStatus);
                    if (changePassword) {
                        pstmt.setString(5, hashedPassword);
                        pstmt.setInt(6, editUserId);
                    } else {
                        pstmt.setInt(5, editUserId);
                    }
                    pstmt.executeUpdate();
                }
            }
        } catch (SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(this,
                "That username is already taken.", "Duplicate Username",
                JOptionPane.WARNING_MESSAGE);
            return;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Database error: " + e.getMessage(), "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this,
            (editUserId == null ? "Staff account created successfully:\n" : "Staff account updated successfully:\n")
            + "Name: " + fullName + "\n"
            + "Username: " + username + "\n"
            + "Role: " + selectedRole,
            editUserId == null ? "Account Created" : "Account Updated", JOptionPane.INFORMATION_MESSAGE);

        java.util.Arrays.fill(passwordChars, '0');
        java.util.Arrays.fill(confirmChars, '0');
        if (parentList != null) {
            parentList.loadUsers();   // refresh the Manage Staff table
        }
        this.dispose();
    }//GEN-LAST:event_btnCreateAccActionPerformed
    private void backToSignIn() {
        if (parentList == null) {
            new Logging().setVisible(true);   // opened from the login screen
        }
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnCashier;
    private javax.swing.JButton btnCreateAcc;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lblfullname;
    private javax.swing.JPasswordField txtconfirm;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
