/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author senub
 */
public class Discount_and_Delivery extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Discount_and_Delivery.class.getName());

    /**
     * Creates new form Discount_and_Loyalty
     */
    public Discount_and_Delivery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Discount_and_Delivery_Plane_text = new javax.swing.JLabel();
        Loyalty_Tiers_and_Delivery_Plane_text = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Delivery_Details_Plane_text = new javax.swing.JLabel();
        Delivery_Address_Plane_Text = new javax.swing.JLabel();
        Delivery_Address_Input = new javax.swing.JTextField();
        Apply_SaveBtn = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel17.setText("jLabel17");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        Discount_and_Delivery_Plane_text.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        Discount_and_Delivery_Plane_text.setForeground(new java.awt.Color(153, 153, 153));
        Discount_and_Delivery_Plane_text.setText("DISCOUNT & DELIVERY");

        Loyalty_Tiers_and_Delivery_Plane_text.setFont(new java.awt.Font("Berlin Sans FB", 0, 21)); // NOI18N
        Loyalty_Tiers_and_Delivery_Plane_text.setText("Loyalty Tiers & Delivery");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Delivery_Details_Plane_text.setText("Delivery Details - ORD - 1043");

        Delivery_Address_Plane_Text.setText("Delivery Address");

        Delivery_Address_Input.addActionListener(this::Delivery_Address_InputActionPerformed);

        Apply_SaveBtn.setBackground(new java.awt.Color(0, 153, 51));
        Apply_SaveBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Apply_SaveBtn.setForeground(new java.awt.Color(255, 255, 255));
        Apply_SaveBtn.setText("Apply & Save");
        Apply_SaveBtn.addActionListener(this::Apply_SaveBtnActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Apply_SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delivery_Address_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delivery_Details_Plane_text)
                    .addComponent(Delivery_Address_Plane_Text))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Delivery_Details_Plane_text)
                .addGap(18, 18, 18)
                .addComponent(Delivery_Address_Plane_Text)
                .addGap(18, 18, 18)
                .addComponent(Delivery_Address_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(Apply_SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Bronz", "0 - 499 pts", "0%", null},
                {"Silver", "500 -1499 pts", "5%", null},
                {"Gold", "1500 +", "10%", null}
            },
            new String [] {
                "TIER", "POINT RANGE", "DISCOUNT", "Edit / Delete"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Discount_and_Delivery_Plane_text)
                            .addComponent(Loyalty_Tiers_and_Delivery_Plane_text, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Discount_and_Delivery_Plane_text)
                .addGap(18, 18, 18)
                .addComponent(Loyalty_Tiers_and_Delivery_Plane_text, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(324, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //error handling Senura
    private void Apply_SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apply_SaveBtnActionPerformed
        String address = Delivery_Address_Input.getText().trim();

    if (address.isEmpty()) {
        // Highlight the field in red
        Delivery_Address_Input.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));

        // Show the error popup
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Delivery address cannot be empty.",
            "Missing Information",
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return; // stop here — don't save anything
    }

    // Field is valid — reset border to normal in case it was red before
    Delivery_Address_Input.setBorder(javax.swing.UIManager.getBorder("TextField.border"));

    // TODO: your actual save logic goes here, e.g.:
    // saveDeliveryDetails(address);
    javax.swing.JOptionPane.showMessageDialog(this, "Saved successfully!");

    }//GEN-LAST:event_Apply_SaveBtnActionPerformed

    private void Delivery_Address_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delivery_Address_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delivery_Address_InputActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Discount_and_Delivery().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Apply_SaveBtn;
    private javax.swing.JTextField Delivery_Address_Input;
    private javax.swing.JLabel Delivery_Address_Plane_Text;
    private javax.swing.JLabel Delivery_Details_Plane_text;
    private javax.swing.JLabel Discount_and_Delivery_Plane_text;
    private javax.swing.JLabel Loyalty_Tiers_and_Delivery_Plane_text;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
