/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CODE.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author senub
 */
public class Discount_and_Delivery extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Discount_and_Delivery.class.getName());

    /**
     * Creates new form Discount_and_Loyalty
     */
    private int orderId;

    public Discount_and_Delivery() {
        this(0); // fallback for NetBeans Design view / no-arg testing — not for real use
    }

    public Discount_and_Delivery(int orderId) {
        initComponents();
        this.orderId = orderId;
        Delivery_Details_Plane_text.setText("Delivery Details - ORD - " + orderId);
        loadLoyaltyTiers();
    }
    
    public void loadLoyaltyTiers() {
        String sql = "SELECT tier_name, min_points, max_points, discount_percentage FROM loyalty_tiers";
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                int min = rs.getInt("min_points");
                Object maxObj = rs.getObject("max_points");
                Integer max = (maxObj == null) ? null : rs.getInt("max_points");
                String range = (max == null) ? min + "+" : min + " - " + max + " pts";
                model.addRow(new Object[]{
                    rs.getString("tier_name"),
                    range,
                    rs.getBigDecimal("discount_percentage") + "%",
                    null
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Failed to load tiers: " + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void saveDeliveryAddress(int orderId, String address) {
        String sql = "INSERT INTO deliveries (order_id, delivery_address, delivery_status) "
                   + "VALUES (?, ?, 'Pending') "
                   + "ON DUPLICATE KEY UPDATE delivery_address = VALUES(delivery_address)";
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, orderId);
            ps.setString(2, address);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Saved successfully!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Failed to save address: " + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Loyalty_Tiers_and_Delivery_Plane_text = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Delivery_Details_Plane_text = new javax.swing.JLabel();
        Delivery_Address_Plane_Text = new javax.swing.JLabel();
        Delivery_Address_Input = new javax.swing.JTextField();
        Apply_SaveBtn = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Discount_and_Delivery_Plane_text = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 245, 242));

        Loyalty_Tiers_and_Delivery_Plane_text.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        Loyalty_Tiers_and_Delivery_Plane_text.setText("Loyalty Tiers & Delivery");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Delivery_Details_Plane_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Delivery_Details_Plane_text.setText("Delivery Details - ORD - 1043");

        Delivery_Address_Plane_Text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Delivery_Address_Plane_Text.setText("Delivery Address");

        Delivery_Address_Input.addActionListener(this::Delivery_Address_InputActionPerformed);

        Apply_SaveBtn.setBackground(new java.awt.Color(11, 107, 109));
        Apply_SaveBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Apply_SaveBtn.setForeground(new java.awt.Color(255, 255, 255));
        Apply_SaveBtn.setText("Apply & Save");
        Apply_SaveBtn.addActionListener(this::Apply_SaveBtnActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Apply_SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delivery_Address_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delivery_Details_Plane_text)
                    .addComponent(Delivery_Address_Plane_Text))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Delivery_Details_Plane_text)
                .addGap(18, 18, 18)
                .addComponent(Delivery_Address_Plane_Text)
                .addGap(34, 34, 34)
                .addComponent(Delivery_Address_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Apply_SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "TIER", "POINT RANGE", "DISCOUNT", "Edit / Delete"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Discount_and_Delivery_Plane_text.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Discount_and_Delivery_Plane_text.setText("DISCOUNT & DELIVERY");

        jButton1.setText("+ New Tier Rule");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Discount_and_Delivery_Plane_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(74, 74, 74))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Discount_and_Delivery_Plane_text))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Loyalty_Tiers_and_Delivery_Plane_text, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Loyalty_Tiers_and_Delivery_Plane_text, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //error handling Senura
    private void Apply_SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apply_SaveBtnActionPerformed
        String address = Delivery_Address_Input.getText().trim();

        if (address.isEmpty()) {
            Delivery_Address_Input.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
            JOptionPane.showMessageDialog(this, "Delivery address cannot be empty.",
                "Missing Information", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Delivery_Address_Input.setBorder(javax.swing.UIManager.getBorder("TextField.border"));

        // Extract the order ID from the header label, e.g. "Delivery Details - ORD - 1043"
        int orderId;
        try {
            String[] parts = Delivery_Details_Plane_text.getText().split("-");
            orderId = Integer.parseInt(parts[parts.length - 1].trim());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Could not determine Order ID.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        saveDeliveryAddress(this.orderId, address);

    }//GEN-LAST:event_Apply_SaveBtnActionPerformed

    private void Delivery_Address_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delivery_Address_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delivery_Address_InputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        New_tier_rule form = new New_tier_rule(this);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Discount_and_Delivery(13).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Apply_SaveBtn;
    private javax.swing.JTextField Delivery_Address_Input;
    private javax.swing.JLabel Delivery_Address_Plane_Text;
    private javax.swing.JLabel Delivery_Details_Plane_text;
    private javax.swing.JLabel Discount_and_Delivery_Plane_text;
    private javax.swing.JLabel Loyalty_Tiers_and_Delivery_Plane_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
