/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author senub
 */
public class New_tier_rule extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(New_tier_rule.class.getName());

    /**
     * Creates new form New_tier_rule
     */
    public New_tier_rule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Discount_and_Delivery_SUB_Interface_Palne_Text = new javax.swing.JLabel();
        New_Tier_Rule_Plane_text = new javax.swing.JLabel();
        Tier_Name_Plane_text = new javax.swing.JLabel();
        Tier_Name_Input = new javax.swing.JTextField();
        Min_Points_Plane_text = new javax.swing.JLabel();
        Max_Points_Input = new javax.swing.JTextField();
        Max_Points_Plane_text = new javax.swing.JLabel();
        Min_Points_Input = new javax.swing.JTextField();
        Discount_Presentaage_Plane_text = new javax.swing.JLabel();
        Discount_Presentaage_Input = new javax.swing.JTextField();
        Save_RuleBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        Discount_and_Delivery_SUB_Interface_Palne_Text.setText("Discount & Delivery - SUB-Interface");

        New_Tier_Rule_Plane_text.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        New_Tier_Rule_Plane_text.setText("New Tier Rule");

        Tier_Name_Plane_text.setText("Tier Name");

        Min_Points_Plane_text.setText("Min Points");

        Max_Points_Input.addActionListener(this::Max_Points_InputActionPerformed);

        Max_Points_Plane_text.setText("Max Points");

        Min_Points_Input.addActionListener(this::Min_Points_InputActionPerformed);

        Discount_Presentaage_Plane_text.setText("Discount Presentaage");

        Save_RuleBtn.setBackground(new java.awt.Color(0, 153, 51));
        Save_RuleBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Save_RuleBtn.setForeground(new java.awt.Color(255, 255, 255));
        Save_RuleBtn.setText("Save Rule");
        Save_RuleBtn.addActionListener(this::Save_RuleBtnActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tier_Name_Plane_text)
                            .addComponent(Tier_Name_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(New_Tier_Rule_Plane_text)
                            .addComponent(Discount_and_Delivery_SUB_Interface_Palne_Text)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Save_RuleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Discount_Presentaage_Plane_text, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(Min_Points_Plane_text)
                                            .addGap(140, 140, 140))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(Min_Points_Input)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Max_Points_Plane_text, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Max_Points_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(Discount_Presentaage_Input)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Discount_and_Delivery_SUB_Interface_Palne_Text)
                .addGap(18, 18, 18)
                .addComponent(New_Tier_Rule_Plane_text)
                .addGap(34, 34, 34)
                .addComponent(Tier_Name_Plane_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tier_Name_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Max_Points_Plane_text)
                    .addComponent(Min_Points_Plane_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Max_Points_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Min_Points_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Discount_Presentaage_Plane_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Discount_Presentaage_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(Save_RuleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(565, 565, 565)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(500, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Max_Points_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Max_Points_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Max_Points_InputActionPerformed

    private void Min_Points_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Min_Points_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Min_Points_InputActionPerformed

    // error handling
    private void Save_RuleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_RuleBtnActionPerformed
    
    String tierName = Tier_Name_Input.getText().trim();
    String minPointsStr = Min_Points_Input.getText().trim();
    String maxPointsStr = Max_Points_Input.getText().trim();
    String discountStr = Discount_Presentaage_Input.getText().trim();

    // 1. Empty checks
    if (tierName.isEmpty()) {
        showError("Tier Name cannot be empty.");
        return;
    }
    if (minPointsStr.isEmpty()) {
        showError("Min Points cannot be empty.");
        return;
    }
    if (maxPointsStr.isEmpty()) {
        showError("Max Points cannot be empty.");
        return;
    }
    if (discountStr.isEmpty()) {
        showError("Discount Percentage cannot be empty.");
        return;
    }

    // 2. Tier Name must be letters only
    if (!tierName.matches("[a-zA-Z ]+")) {
        showError("Tier Name can only contain letters.");
        return;
    }

    // 3. Min/Max Points must be whole numbers
    int minPoints, maxPoints;
    try {
        minPoints = Integer.parseInt(minPointsStr);
        maxPoints = Integer.parseInt(maxPointsStr);
    } catch (NumberFormatException e) {
        showError("Min Points and Max Points must be whole numbers.");
        return;
    }

    // 4. Discount must be a float
    float discount;
    try {
        discount = Float.parseFloat(discountStr);
    } catch (NumberFormatException e) {
        showError("Discount Percentage must be a number (e.g. 5 or 5.5).");
        return;
    }

    // 5. (Optional) logical check
    if (minPoints >= maxPoints) {
        showError("Min Points must be less than Max Points.");
        return;
    }

    // 6. All valid — save the new tier rule here
    // TODO: e.g. insert {tierName, minPoints, maxPoints, discount} into your tiers table/model
    javax.swing.JOptionPane.showMessageDialog(this, "Tier rule saved successfully!");
}

private void showError(String message) {
    javax.swing.JOptionPane.showMessageDialog(
        this,
        message,
        "Invalid Input",
        javax.swing.JOptionPane.WARNING_MESSAGE
    );
    }//GEN-LAST:event_Save_RuleBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new New_tier_rule().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Discount_Presentaage_Input;
    private javax.swing.JLabel Discount_Presentaage_Plane_text;
    private javax.swing.JLabel Discount_and_Delivery_SUB_Interface_Palne_Text;
    private javax.swing.JTextField Max_Points_Input;
    private javax.swing.JLabel Max_Points_Plane_text;
    private javax.swing.JTextField Min_Points_Input;
    private javax.swing.JLabel Min_Points_Plane_text;
    private javax.swing.JLabel New_Tier_Rule_Plane_text;
    private javax.swing.JToggleButton Save_RuleBtn;
    private javax.swing.JTextField Tier_Name_Input;
    private javax.swing.JLabel Tier_Name_Plane_text;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
