/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author User
 */
public class OrderReview extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrderReview.class.getName());

    /**
     * Creates new form OrderReview
     */
    public OrderReview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        OrderReviewLable = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CustomerDetailsLable = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        CustomerName = new javax.swing.JLabel();
        LoyaltyDiscountLable = new javax.swing.JLabel();
        OrderItemsLabel = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        ProductLable = new java.awt.Label();
        QtyLable = new java.awt.Label();
        UnitPriceLable = new javax.swing.JLabel();
        LineTotalLable = new javax.swing.JLabel();
        FulfillmentModeLable = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        PickupBtn = new javax.swing.JButton();
        DeliveryBtn = new javax.swing.JButton();
        SubtotalLable = new javax.swing.JLabel();
        LoyaltyDiscountPresentage = new javax.swing.JLabel();
        DeliveryFeeLabel = new javax.swing.JLabel();
        Subtotal = new javax.swing.JLabel();
        LoyaltyDiscount = new javax.swing.JLabel();
        DeliveryFee = new javax.swing.JLabel();
        TotalAmountLabel = new javax.swing.JLabel();
        TotalAmount = new javax.swing.JLabel();
        EditOrderBtn = new javax.swing.JButton();
        ConfirmOrderBtn = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 243, 240));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        OrderReviewLable.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        OrderReviewLable.setText("Order Review");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(OrderReviewLable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(OrderReviewLable)
                .addGap(15, 15, 15))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        CustomerDetailsLable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CustomerDetailsLable.setText("Customer Details");

        jPanel4.setBackground(new java.awt.Color(245, 243, 240));

        CustomerName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CustomerName.setText("Customer Name");

        LoyaltyDiscountLable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LoyaltyDiscountLable.setText("Loyalty discount applied: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addComponent(LoyaltyDiscountLable, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerName)
                    .addComponent(LoyaltyDiscountLable, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        OrderItemsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        OrderItemsLabel.setText("Order Items");

        ProductLable.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ProductLable.setText("Product");

        QtyLable.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        QtyLable.setText("Qty");

        UnitPriceLable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UnitPriceLable.setText("Unit Price");

        LineTotalLable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LineTotalLable.setText("Line Total");

        FulfillmentModeLable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FulfillmentModeLable.setText("Fulfillment Mode");

        jPanel5.setBackground(new java.awt.Color(245, 243, 240));

        PickupBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PickupBtn.setText("Pickup");
        PickupBtn.addActionListener(this::PickupBtnActionPerformed);

        DeliveryBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DeliveryBtn.setText("Delivery");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(PickupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DeliveryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PickupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeliveryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        SubtotalLable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SubtotalLable.setText("Subtotal");

        LoyaltyDiscountPresentage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoyaltyDiscountPresentage.setText("Loyalty Discount");

        DeliveryFeeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeliveryFeeLabel.setText("Delivery Fee");

        Subtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Subtotal.setText("Subtotal");

        LoyaltyDiscount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoyaltyDiscount.setText("Loyalty Discount");

        DeliveryFee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeliveryFee.setText("DeliveryFee");

        TotalAmountLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TotalAmountLabel.setText("Total Amount");

        TotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TotalAmount.setText("Total Amount");

        EditOrderBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EditOrderBtn.setText("Edit Order");

        ConfirmOrderBtn.setBackground(new java.awt.Color(26, 92, 94));
        ConfirmOrderBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ConfirmOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmOrderBtn.setText("Confirm Order");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(ProductLable, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(457, 457, 457)
                .addComponent(QtyLable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(UnitPriceLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LineTotalLable)
                .addGap(145, 145, 145))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomerDetailsLable)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderItemsLabel)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FulfillmentModeLable))
                            .addGap(226, 226, 226)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DeliveryFeeLabel)
                                            .addComponent(TotalAmountLabel))
                                        .addGap(261, 261, 261))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(EditOrderBtn)
                                        .addGap(37, 37, 37)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(LoyaltyDiscountPresentage, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(216, 216, 216))
                                .addComponent(SubtotalLable, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LoyaltyDiscount)
                                .addComponent(Subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ConfirmOrderBtn)
                                .addComponent(DeliveryFee)
                                .addComponent(TotalAmount))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CustomerDetailsLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrderItemsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ProductLable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(QtyLable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UnitPriceLable)
                        .addComponent(LineTotalLable)))
                .addGap(1, 1, 1)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubtotalLable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Subtotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LoyaltyDiscountPresentage)
                            .addComponent(LoyaltyDiscount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeliveryFeeLabel)
                            .addComponent(DeliveryFee))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalAmountLabel)
                            .addComponent(TotalAmount)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(FulfillmentModeLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditOrderBtn)
                    .addComponent(ConfirmOrderBtn))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PickupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickupBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PickupBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OrderReview().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmOrderBtn;
    private javax.swing.JLabel CustomerDetailsLable;
    private javax.swing.JLabel CustomerName;
    private javax.swing.JButton DeliveryBtn;
    private javax.swing.JLabel DeliveryFee;
    private javax.swing.JLabel DeliveryFeeLabel;
    private javax.swing.JButton EditOrderBtn;
    private javax.swing.JLabel FulfillmentModeLable;
    private javax.swing.JLabel LineTotalLable;
    private javax.swing.JLabel LoyaltyDiscount;
    private javax.swing.JLabel LoyaltyDiscountLable;
    private javax.swing.JLabel LoyaltyDiscountPresentage;
    private javax.swing.JLabel OrderItemsLabel;
    private javax.swing.JLabel OrderReviewLable;
    private javax.swing.JButton PickupBtn;
    private java.awt.Label ProductLable;
    private java.awt.Label QtyLable;
    private javax.swing.JLabel Subtotal;
    private javax.swing.JLabel SubtotalLable;
    private javax.swing.JLabel TotalAmount;
    private javax.swing.JLabel TotalAmountLabel;
    private javax.swing.JLabel UnitPriceLable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
